### ISSUE TITLE
Unfortunately !! My Students and I Are Studying Code In MicroPython!! (Lego Official Python code)

### ISSUE THREAD

**Issue by deopark** [KWSmit/Pixy_ev3dev#6]
Can I See Your Code Using MicroPython ?? as Below....

#!/usr/bin/env pybricks-micropython
from pybricks.hubs import EV3Brick
from pybricks.ev3devices import Motor
from pybricks.parameters import Port

...

# Thank You

**Comment by KWSmit** [comment]
Sure you can, all my code is published under the MIT licennse.

Regards,
Kees

**Comment by KWSmit** [comment]
> Can I See Your Code Using MicroPython ?? as Below....
> 
> #!/usr/bin/env pybricks-micropython from pybricks.hubs import EV3Brick from pybricks.ev3devices import Motor from pybricks.parameters import Port
> 
> ...
> # Thank You

Have a look at my repo [pixy2-pybricks](https://github.com/KWSmit/pixy2_pybricks) which is using micropython.
Excuse me for my late reaction, apparently my notification settings are not correct...
