### ISSUE TITLE
Connection to Pixy2 cam

### ISSUE THREAD

**Issue by jianwen-android** [KWSmit/Pixy_ev3dev#7]
Hi, my team is using the Pixycam2 and ev3dev for our competition, so first of all thank you for the examples and the tutorial.

However, we are having trouble connecting the camera to the robot. We followed this connection guide https://docs.pixycam.com/wiki/doku.php?id=wiki:v2:diy_lego_cable
and made our own cable. However, the ev3 doesn't seem to read any i2c devices at the port we put it at.

I made sure that we were using the right SMBus and input port, so I'm wondering maybe its a problem with the cable. If you don't mind, can you share how you connecting the camera to the ev3? Much appreciated in advance

**Comment by KWSmit** [comment]
Hi,
I own a [Pixy2 for LEGO Mindstorms EV3](https://docs.pixycam.com/wiki/doku.php?id=wiki:v2:lego_wiki) and use the cable that comes with this model.

**Comment by jianwen-android** [comment]
Ok, thank you so much for the repository and the reply :)
